In [1]:
!python -m wget https://raw.githubusercontent.com/karpathy/ng-video-lecture/master/input.txt


Saved under input (6).txt


In [2]:
with open ('data/input.txt', 'r', encoding='utf-8') as f:
    text = f.read()

In [3]:
print(f"Length of Dataset in Characters: {len(text)}")

Length of Dataset in Characters: 1115394


In [4]:
print(text[:1000])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.

All:
We know't, we know't.

First Citizen:
Let us kill him, and we'll have corn at our own price.
Is't a verdict?

All:
No more talking on't; let it be done: away, away!

Second Citizen:
One word, good citizens.

First Citizen:
We are accounted poor citizens, the patricians good.
What authority surfeits on would relieve us: if they
would yield us but the superfluity, while it were
wholesome, we might guess they relieved us humanely;
but they think we are too dear: the leanness that
afflicts us, the object of our misery, is as an
inventory to particularise their abundance; our
sufferance is a gain to them Let us revenge this with
our pikes, ere we become rakes: for the gods know I
speak this in hunger for bread, not in thirst for revenge.



In [5]:
# set takes all the characters from text -> it is made into a list -> and sorted
chars = sorted(list(set(text)))
vocab_size = len(chars)

print(''.join(chars))
print(f'Number of Charactes: {vocab_size}')


 !$&',-.3:;?ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz
Number of Charactes: 65


In [6]:
test = enumerate(chars)
print(dict(test))

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


In [7]:
stoi = {ch:i for i,ch in enumerate(chars)}
itos = dict(enumerate(chars))

In [8]:
print(stoi)

{'\n': 0, ' ': 1, '!': 2, '$': 3, '&': 4, "'": 5, ',': 6, '-': 7, '.': 8, '3': 9, ':': 10, ';': 11, '?': 12, 'A': 13, 'B': 14, 'C': 15, 'D': 16, 'E': 17, 'F': 18, 'G': 19, 'H': 20, 'I': 21, 'J': 22, 'K': 23, 'L': 24, 'M': 25, 'N': 26, 'O': 27, 'P': 28, 'Q': 29, 'R': 30, 'S': 31, 'T': 32, 'U': 33, 'V': 34, 'W': 35, 'X': 36, 'Y': 37, 'Z': 38, 'a': 39, 'b': 40, 'c': 41, 'd': 42, 'e': 43, 'f': 44, 'g': 45, 'h': 46, 'i': 47, 'j': 48, 'k': 49, 'l': 50, 'm': 51, 'n': 52, 'o': 53, 'p': 54, 'q': 55, 'r': 56, 's': 57, 't': 58, 'u': 59, 'v': 60, 'w': 61, 'x': 62, 'y': 63, 'z': 64}


In [9]:
print(itos)

{0: '\n', 1: ' ', 2: '!', 3: '$', 4: '&', 5: "'", 6: ',', 7: '-', 8: '.', 9: '3', 10: ':', 11: ';', 12: '?', 13: 'A', 14: 'B', 15: 'C', 16: 'D', 17: 'E', 18: 'F', 19: 'G', 20: 'H', 21: 'I', 22: 'J', 23: 'K', 24: 'L', 25: 'M', 26: 'N', 27: 'O', 28: 'P', 29: 'Q', 30: 'R', 31: 'S', 32: 'T', 33: 'U', 34: 'V', 35: 'W', 36: 'X', 37: 'Y', 38: 'Z', 39: 'a', 40: 'b', 41: 'c', 42: 'd', 43: 'e', 44: 'f', 45: 'g', 46: 'h', 47: 'i', 48: 'j', 49: 'k', 50: 'l', 51: 'm', 52: 'n', 53: 'o', 54: 'p', 55: 'q', 56: 'r', 57: 's', 58: 't', 59: 'u', 60: 'v', 61: 'w', 62: 'x', 63: 'y', 64: 'z'}


In [10]:
encode = lambda s: [stoi[c] for c in s]
decoder = lambda l: ''.join([itos[i] for i in l])

In [11]:
def encoder(s):
    return [stoi[c] for c in s]

In [12]:
def decoder(l):
    return ''.join([itos[i] for i in l])

In [13]:
print(encode('Hi There!'))
print(decoder(encoder('Hi There!')))

[20, 47, 1, 32, 46, 43, 56, 43, 2]
Hi There!


In [14]:
import torch
data = torch.tensor(encoder(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

torch.Size([1115394]) torch.int64
tensor([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52, 63,
         1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51, 43,  1,
        57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54, 43, 39, 49,
         6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57, 58,  1, 15, 47,
        58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1, 39, 56, 43,  1, 39, 50, 50,
         1, 56, 43, 57, 53, 50, 60, 43, 42,  1, 56, 39, 58, 46, 43, 56,  1, 58,
        53,  1, 42, 47, 43,  1, 58, 46, 39, 52,  1, 58, 53,  1, 44, 39, 51, 47,
        57, 46, 12,  0,  0, 13, 50, 50, 10,  0, 30, 43, 57, 53, 50, 60, 43, 42,
         8,  1, 56, 43, 57, 53, 50, 60, 43, 42,  8,  0,  0, 18, 47, 56, 57, 58,
         1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 18, 47, 56, 57, 58,  6,  1, 63,
        53, 59,  1, 49, 52, 53, 61,  1, 15, 39, 47, 59, 57,  1, 25, 39, 56, 41,
      

In [15]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [16]:
split = int(0.8 * len(data))
train_data = data[:split]
valid_data = data[split:]

In [17]:
print(len(train_data))
print(len(valid_data))

892315
223079


In [18]:
# Hyperparameter - block size
block_size = 8
train_data[:block_size+1]

tensor([18, 47, 56, 57, 58,  1, 15, 47, 58])

In [19]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"Whenever input is {context} -- target is {target}")

print(f"\nX Data: {x}")
print(f"Y Data: {y}")

Whenever input is tensor([18]) -- target is 47
Whenever input is tensor([18, 47]) -- target is 56
Whenever input is tensor([18, 47, 56]) -- target is 57
Whenever input is tensor([18, 47, 56, 57]) -- target is 58
Whenever input is tensor([18, 47, 56, 57, 58]) -- target is 1
Whenever input is tensor([18, 47, 56, 57, 58,  1]) -- target is 15
Whenever input is tensor([18, 47, 56, 57, 58,  1, 15]) -- target is 47
Whenever input is tensor([18, 47, 56, 57, 58,  1, 15, 47]) -- target is 58

X Data: tensor([18, 47, 56, 57, 58,  1, 15, 47])
Y Data: tensor([47, 56, 57, 58,  1, 15, 47, 58])


What we're essentially going for in this section is that we want to always get the targets. What we're doing is always shifting right for the target because that is what we want to predict. So the target is always one step ahead. That is why we have *1:block_size*. When it comes to +1, it's that we also need the target for the last token in the sequence. So we have to grab the next token from the next sequence. 

So for block_size, the last +1 means that we have a target for the last token in the sequence. BUT we don't use the +1 as input context. The +1 is used as a target ONLY. See how the X and Y data have the same length but Y is shifted to the right at one position. So the 

In [20]:
len(data)

1115394

In [21]:
torch.manual_seed(1337)
batch_size = 4 # How many sequences in one batch 
block_size = 8 # Maximum length of a sequence

def get_batch(split):
    data = train_data if "train" else valid_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    xb = torch.stack([data[i:i+block_size] for i in ix])
    yb = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return xb,yb

In [22]:
ix = torch.randint(len(data) - block_size, (batch_size,))
print(ix)

tensor([1078327,  453969,   41646,  671252])


In [23]:
xb = torch.stack([data[i:i+block_size] for i in ix])
print(xb)

tensor([[59, 52, 49, 47, 52, 42,  1, 40],
        [53, 54, 43, 44, 59, 50,  1, 50],
        [27, 24, 33, 25, 26, 21, 13, 10],
        [47, 41, 43,  1, 53, 60, 43, 56]])


In [24]:
yb = torch.stack([data[i+1:i+block_size+1] for i in ix])
print(yb)

tensor([[52, 49, 47, 52, 42,  1, 40, 56],
        [54, 43, 44, 59, 50,  1, 50, 39],
        [24, 33, 25, 26, 21, 13, 10,  0],
        [41, 43,  1, 53, 60, 43, 56, 58]])


In [25]:
xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)
print(f'\n')

inputs:
torch.Size([4, 8])
tensor([[43, 56, 63,  1, 47, 52,  1, 46],
        [44, 47, 45, 46, 58,  1, 40, 43],
        [58, 46, 43, 56,  8,  0,  0, 24],
        [ 6,  0, 21,  1, 52, 43, 60, 43]])
targets:
torch.Size([4, 8])
tensor([[56, 63,  1, 47, 52,  1, 46, 47],
        [47, 45, 46, 58,  1, 40, 43,  1],
        [46, 43, 56,  8,  0,  0, 24, 17],
        [ 0, 21,  1, 52, 43, 60, 43, 56]])




In [26]:
xb

tensor([[43, 56, 63,  1, 47, 52,  1, 46],
        [44, 47, 45, 46, 58,  1, 40, 43],
        [58, 46, 43, 56,  8,  0,  0, 24],
        [ 6,  0, 21,  1, 52, 43, 60, 43]])

In [27]:
for b in range(batch_size):
    for t in range(block_size):
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"Context: {context.tolist()} -> Target: {target}")

Context: [43] -> Target: 56
Context: [43, 56] -> Target: 63
Context: [43, 56, 63] -> Target: 1
Context: [43, 56, 63, 1] -> Target: 47
Context: [43, 56, 63, 1, 47] -> Target: 52
Context: [43, 56, 63, 1, 47, 52] -> Target: 1
Context: [43, 56, 63, 1, 47, 52, 1] -> Target: 46
Context: [43, 56, 63, 1, 47, 52, 1, 46] -> Target: 47
Context: [44] -> Target: 47
Context: [44, 47] -> Target: 45
Context: [44, 47, 45] -> Target: 46
Context: [44, 47, 45, 46] -> Target: 58
Context: [44, 47, 45, 46, 58] -> Target: 1
Context: [44, 47, 45, 46, 58, 1] -> Target: 40
Context: [44, 47, 45, 46, 58, 1, 40] -> Target: 43
Context: [44, 47, 45, 46, 58, 1, 40, 43] -> Target: 1
Context: [58] -> Target: 46
Context: [58, 46] -> Target: 43
Context: [58, 46, 43] -> Target: 56
Context: [58, 46, 43, 56] -> Target: 8
Context: [58, 46, 43, 56, 8] -> Target: 0
Context: [58, 46, 43, 56, 8, 0] -> Target: 0
Context: [58, 46, 43, 56, 8, 0, 0] -> Target: 24
Context: [58, 46, 43, 56, 8, 0, 0, 24] -> Target: 17
Context: [6] -> Ta

In [28]:
xb[1].tolist()

[44, 47, 45, 46, 58, 1, 40, 43]

In [29]:
xb.shape

torch.Size([4, 8])

In [30]:
print(decoder(xb[3].tolist()))

,
I neve


In [31]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):
    def __init__(self, vocab_size:int):
        super().__init__()
        # nn.Embedding requires the actual number of vocab_size (characters being used) for the first argument
        # second argument is a hyperparameter that dictates the length of the embedding vector
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx):
        logits = self.token_embedding_table(idx)
        return logits

    def generate(self, idx, max_new_tokens):
        for _ in range(max_new_tokens):
            # Shape of BTC 
            logits = self(idx)
            # Select last token in sequence to predict next token - transforms to BC. We are currently
            # working with the batch of the last token in the sequence's logits. 
            logits = logits[:,-1]
            # We get the probabilities with softmax on the logits
            probs = F.softmax(logits, dim=1)
            # We predict the next token
            idx_next = torch.multinomial(probs, num_samples=1)
            # We concatenate the new token to idx - adding to the sequence B,T+1
            idx = torch.cat((idx, idx_next), dim=1)
        return idx
        
model = BigramLanguageModel(vocab_size)
logits = model(xb)
print(decoder(model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


Sr?qP-QWktXoL&jLDJgOLVz'RIoDqHdhsV&vLLxatjscMpwLERSPyao.qfzs$Ys$zF-w,;eEkzxjgCKFChs!iWW.ObzDnxA Ms$3


In [32]:
logits, logits.shape

(tensor([[[ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594],
          [-0.6722,  0.2322, -0.1632,  ...,  0.1390,  0.7560,  0.4296],
          [-0.8109,  0.2410, -0.1139,  ...,  1.4509,  0.1836,  0.3064],
          ...,
          [-0.2103,  0.4481,  1.2381,  ...,  1.3597, -0.0821,  0.3909],
          [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
          [ 1.0901,  0.2170, -2.9996,  ..., -0.5472, -0.8017,  0.7761]],
 
         [[ 1.0541,  1.5018, -0.5266,  ...,  1.8574,  1.5249,  1.3035],
          [ 1.6515, -0.0424, -0.7355,  ...,  0.8682,  2.0593, -0.8159],
          [ 0.6635,  0.2673, -0.0410,  ..., -0.5861, -1.0893,  0.1948],
          ...,
          [ 0.5978, -0.0514, -0.0646,  ..., -1.4649, -2.0555,  1.8275],
          [ 1.4311,  0.4160, -2.2246,  ...,  0.7330,  0.3551,  0.1472],
          [ 0.3323, -0.0872, -0.7470,  ..., -0.6716, -0.9572, -0.9594]],
 
         [[ 0.2475, -0.6349, -1.2909,  ...,  1.3064, -0.2256, -1.8305],
          [ 1.0901,  0.2170,

In [33]:
print(logits[:,-1,:])
print(logits[:,-1,:].shape)

tensor([[ 1.0901,  0.2170, -2.9996,  1.4690, -0.1948, -0.1507,  0.2601, -0.9647,
          0.1162, -0.8295, -0.2266,  0.0219, -0.2785, -0.4851, -1.8023, -0.7330,
         -1.2828,  0.8863,  1.0515, -0.9823, -1.6369, -1.3499,  0.1830,  0.0532,
         -1.1438, -0.2829, -0.5979,  1.4757,  0.4655, -3.0346,  0.5516,  1.3107,
          0.1240, -1.8046,  0.2700, -0.4322,  0.2784, -0.5599,  1.2502,  0.7051,
         -1.0169,  0.4854, -1.0808, -0.3128, -0.4189, -0.5718,  0.8215,  1.7384,
          0.5578,  0.6167,  1.5260, -0.3508, -1.5615,  0.4548, -0.8935,  0.3642,
          0.5714,  2.7072, -1.5443,  1.1288, -1.1217, -1.7328, -0.5472, -0.8017,
          0.7761],
        [ 0.3323, -0.0872, -0.7470, -0.6074,  0.3418,  0.5343,  0.3957, -0.4919,
         -0.0894, -1.3886,  1.2835, -0.3975,  2.0152,  1.6773, -0.3833,  1.5728,
          1.9458,  0.7247, -0.4834, -0.3263,  0.3193, -0.4198, -0.6435, -0.3311,
          0.7554, -1.2385,  0.4067,  0.9982, -0.6511,  1.2450,  0.2804,  0.8371,
         

In [34]:
for i in range(2):
    idx = logits
    print(logits.shape)
    check = logits[:,-1]
    print(check.shape)
    probs = F.softmax(check, dim=1)
    print(probs.shape)
    idx_next = torch.multinomial(probs, num_samples=1)
    print(idx_next.shape)
    print(idx_next)
    print(xb.shape)
    idx = torch.cat((xb, idx_next), dim=1)
    print(idx.shape)

torch.Size([4, 8, 65])
torch.Size([4, 65])
torch.Size([4, 65])
torch.Size([4, 1])
tensor([[22],
        [42],
        [31],
        [ 8]])
torch.Size([4, 8])
torch.Size([4, 9])
torch.Size([4, 8, 65])
torch.Size([4, 65])
torch.Size([4, 65])
torch.Size([4, 1])
tensor([[42],
        [ 0],
        [54],
        [20]])
torch.Size([4, 8])
torch.Size([4, 9])


In [35]:
loss_fn = nn.CrossEntropyLoss()
loss = loss_fn(logits.view(4*8,65), yb.view(4*8))
loss

tensor(4.5193, grad_fn=<NllLossBackward0>)

In [36]:
optim = torch.optim.AdamW(model.parameters(), lr=1e-3)

In [37]:
xb, yb = get_batch('train')

In [38]:
def train_step(model, train, target, epochs, device, loss_fn, optim):
    data.to(device)
    for epoch in range(epochs):
        model.train()
        logits = model(train)
        loss = loss_fn(logits.view(4*8,65), target.view(4*8))
        optim.zero_grad
        loss.backward()
        optim.step()
        if epoch % 1000 == 0:
            print(loss.item())
    

In [39]:
train_step(model, xb, yb, 3000, device, loss_fn, optim)

4.4506940841674805
1.8645155429840088
0.8274747729301453


In [40]:
print((model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)))
print((model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)).shape)
print((model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)[0]))
print((model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)[0]).shape)
print((model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)[0].tolist()))

tensor([[ 0, 37, 27, 30, 48, 22, 63, 42, 53, 41, 49,  1, 58, 46, 56, 53, 41, 49,
          8,  0,  0, 37, 35, 31, 64, 28, 26, 62, 40, 48, 28, 47, 41, 49,  8,  0,
         37, 27, 30, 48, 11, 60, 35, 56, 53, 58, 43, 57, 42, 53, 41, 49,  8,  0,
         37, 27, 30, 56, 53, 41, 50, 53, 58, 43, 57, 42, 53, 51,  1, 54, 56, 53,
         51,  1, 54, 56, 53, 51,  1, 58, 46, 39, 57, 42,  3, 24, 48, 11, 12, 63,
         64, 63, 33, 41, 50, 53, 41, 50, 53, 58, 46, 57, 42, 38, 29, 45, 15,  7,
         46, 50, 53, 41, 49,  1, 58, 43, 57, 42, 53, 41, 49,  8,  0, 37, 27, 30,
         22,  1, 21, 57, 42, 53, 51,  1, 58, 46, 28, 57, 42, 53, 58, 43, 57, 42,
         53, 41, 49,  1, 54, 56, 53, 41, 49,  1, 54, 56, 53, 58, 46, 63,  5, 46,
         38, 15, 35, 46, 59,  8,  0, 37, 27, 30, 48, 28,  1, 41, 49,  8,  0, 37,
         27, 30, 54, 56, 53, 58, 46, 57, 42, 53, 41, 49,  8,  0,  0,  0, 37, 27,
         30, 53, 41]])
torch.Size([1, 201])
tensor([ 0,  0,  0, 37, 27, 30, 48, 42, 53, 51,  1, 61, 39, 57, 4

In [41]:
print(decoder(model.generate(torch.zeros((1,1), dtype=torch.long), max_new_tokens=200)[0].tolist()))


YORrock protesdom I I I ck.
YORV;JYORCb;hRj,F'zI prothuKth$?,Sesdock I I ck tesdom proclotesdom proclock.

YORjQFJg ck.
YORvck.

YORV$Sqcloclock prom wasdock proclotesdothR,FqprothSwasdotesdothsdocloc


In [42]:
torch.zeros(50)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.])

In [43]:
batch_loss = {}
for split in ['train', 'test']:
    batch_loss[split] = 5

print(batch_loss)

{'train': 5, 'test': 5}


In [44]:
torch.manual_seed(1337)
B,T,C = 4,8,2
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [45]:
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        print(f"\n{xprev}")
        xbow[b,t] = torch.mean(xprev, 0)
        print(xbow[0])


tensor([[ 0.1808, -0.0700]])
tensor([[ 0.1808, -0.0700],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152]])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255]])
tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]])

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643]])
tensor([[ 0.1808, -0.0700],
        [

In [46]:
x[0]

tensor([[ 0.1808, -0.0700],
        [-0.3596, -0.9152],
        [ 0.6258,  0.0255],
        [ 0.9545,  0.0643],
        [ 0.3612,  1.1679],
        [-1.3499, -0.5102],
        [ 0.2360, -0.2398],
        [-0.9211,  1.5433]])

In [47]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [48]:
xbow.shape

torch.Size([4, 8, 2])

In [49]:
import statistics
data1 = [0.1808, -0.3596]
check = statistics.mean(data1)
check

-0.0894

In [50]:
a = torch.tril(torch.ones((3,3)))
print(a.shape)
print(a)
a = a / torch.sum(a, 1, keepdim=True)
print(a.shape)
print(a)

torch.Size([3, 3])
tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])
torch.Size([3, 3])
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])


In [51]:
# PARAMETER EXPLANATIONS FOR torch.sum()

# If we change the dimension to 0 - then the operations will be conducted column-wise
# as compared to 1 - which makes the operations happen row-wise

# If keepdim=False, broadcasting occurs, which turns the operation into:

# tensor([[1.0000 / 1., 0.0000 / 2., 0.0000 / 3.],
#         [1.0000 / 1., 1.0000 / 2., 0.0000 / 3.],
#         [1.0000 / 1., 1.0000 / 2., 1.0000 / 3.]])

# Output:

# tensor([[1.0000, 0.0000, 0.0000],
#         [1.0000, 0.5000, 0.0000],
#         [1.0000, 0.5000, 0.3333]])

# If keepdim=True, broadcasting doesn't occur, which turns the operation into:

# tensor([[1.0000 / 1., 0.0000 / 1., 0.0000 / 1.],
#         [1.0000 / 2., 1.0000 / 2., 0.0000 / 2.],
#         [1.0000 / 3., 1.0000 / 3., 1.0000 / 3.]])

# Output:

# tensor([[1.0000, 0.0000, 0.0000],
#         [0.5000, 0.5000, 0.0000],
#         [0.3333, 0.3333, 0.3333]])

In [52]:
weights = torch.tril(torch.ones((T,T)))
weights = weights / torch.sum(weights, 1, keepdim=True)
print(weights.shape)
# PyTorch broadcasting aligns dimensions from right to left.
# The original shape of weights is (T, T), which does not match with (B, T, C).
# PyTorch aligns the rightmost dimensions first, so (T, T) is paired with (T, C).
# Since B does not have a pair, PyTorch adds a dimension to the leftmost position of (T, T),
# resulting in (B, T, T).
xbow2 = weights @ x  # (B, T, T) @ (B, T, C) ----> (B, T, C)
print(xbow.shape)
torch.allclose(xbow, xbow2)

torch.Size([8, 8])
torch.Size([4, 8, 2])


False

In [53]:
xbow[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [54]:
xbow2[0]

tensor([[ 0.1808, -0.0700],
        [-0.0894, -0.4926],
        [ 0.1490, -0.3199],
        [ 0.3504, -0.2238],
        [ 0.3525,  0.0545],
        [ 0.0688, -0.0396],
        [ 0.0927, -0.0682],
        [-0.0341,  0.1332]])

In [73]:
B,T,C = 4,8,32
x = torch.randn(B,T,C)

# Single Head performing self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x) # (B,T,16)
q = query(x) # (B,T,16)
wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) = (B, T, T)
# wei = q @ k.transpose(-2, -1) / head_size**0.5
# The above code scales the dot product of q and k by the inverse of the square root of the head size.
# This scaling prevents the softmax function from producing extremely large values,
# which would cause it to assign very high attention to a few tokens and very low attention to others.
# By scaling, we ensure a more balanced distribution of attention across tokens.

tril = torch.tril(torch.ones((T,T)))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x) # (B,T,16)
out = wei @ v

out.shape

torch.Size([4, 8, 16])

In [74]:
wei

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5014, 0.4986, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1014, 0.7953, 0.1034, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0268, 0.2879, 0.4719, 0.2135, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5155, 0.0233, 0.0411, 0.0320, 0.3882, 0.0000, 0.0000, 0.0000],
         [0.0448, 0.0413, 0.0044, 0.0041, 0.6730, 0.2324, 0.0000, 0.0000],
         [0.0059, 0.1334, 0.7885, 0.0345, 0.0116, 0.0086, 0.0175, 0.0000],
         [0.0774, 0.0630, 0.1206, 0.0612, 0.1398, 0.3568, 0.0496, 0.1316]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4486, 0.5514, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.9896, 0.0085, 0.0019, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0567, 0.4144, 0.2391, 0.2898, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0240, 0.0510, 0.8162, 0.0149, 0.0940, 0.0000, 0.0000, 0.0000],
         [0.0542, 0.128