In [1]:
import torch

In [2]:
x = torch.rand([7,7])
x.shape

torch.Size([7, 7])

In [3]:
y = torch.rand([1,7])
y.shape

torch.Size([1, 7])

In [4]:
result = x @ y.T
result.shape, result.ndim

(torch.Size([7, 1]), 2)

In [5]:
random_seed = 0

In [6]:
torch.manual_seed(seed=random_seed)
x = torch.rand(7,7)
print(x)
x.shape, x.ndim

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])


(torch.Size([7, 7]), 2)

In [7]:
torch.manual_seed(seed=random_seed)
y = torch.rand(1,7)
print(y)
y.shape, y.ndim

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


(torch.Size([1, 7]), 2)

In [8]:
result = x @ y.T
result, result.shape

(tensor([[1.5985],
         [1.1173],
         [1.2741],
         [1.6838],
         [0.8279],
         [1.0347],
         [1.2498]]),
 torch.Size([7, 1]))

In [9]:
torch.cuda.manual_seed(1234)

In [10]:
device = 'cuda'
torch.manual_seed(seed=1234)
x = torch.rand(2,3).to(device)
x.shape, x.device

(torch.Size([2, 3]), device(type='cuda', index=0))

In [11]:
y = torch.rand(2,3).to(device)
y.shape, y.device

(torch.Size([2, 3]), device(type='cuda', index=0))

In [12]:
x, y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))

In [13]:
result = x @ y.T
result, result.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

In [14]:
max = result.max()
min = result.min()
max, min

(tensor(0.5617, device='cuda:0'), tensor(0.3647, device='cuda:0'))

In [15]:
maxIndex = result.argmax()
minIndex = result.argmin()
maxIndex, minIndex

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))

In [16]:
torch.manual_seed(seed=7)
x = torch.rand(1,1,1,10)
x_squeezed = x.squeeze()
x_squeezed, x_squeezed.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))